# reference. https://api.slack.com/events
- service_name: example
  type: reaction_added
  users:
    - s_ishii
  item_channels:
    - "development"
  reactions:
    - "ok_hand"
- service_name: impersonate
  type: app_mention
  users:
    - s_ishii
  item_channels:
    - development