// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package chatbot

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatbotClient is the client API for Chatbot service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatbotClient interface {
	Reply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type chatbotClient struct {
	cc grpc.ClientConnInterface
}

func NewChatbotClient(cc grpc.ClientConnInterface) ChatbotClient {
	return &chatbotClient{cc}
}

func (c *chatbotClient) Reply(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/chatbot.Chatbot/Reply", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ChatbotServer is the server API for Chatbot service.
// All implementations must embed UnimplementedChatbotServer
// for forward compatibility
type ChatbotServer interface {
	Reply(context.Context, *Request) (*Result, error)
	mustEmbedUnimplementedChatbotServer()
}

// UnimplementedChatbotServer must be embedded to have forward compatible implementations.
type UnimplementedChatbotServer struct {
}

func (UnimplementedChatbotServer) Reply(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedChatbotServer) mustEmbedUnimplementedChatbotServer() {}

// UnsafeChatbotServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatbotServer will
// result in compilation errors.
type UnsafeChatbotServer interface {
	mustEmbedUnimplementedChatbotServer()
}

func RegisterChatbotServer(s grpc.ServiceRegistrar, srv ChatbotServer) {
	s.RegisterService(&Chatbot_ServiceDesc, srv)
}

func _Chatbot_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatbotServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatbot.Chatbot/Reply",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatbotServer).Reply(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Chatbot_ServiceDesc is the grpc.ServiceDesc for Chatbot service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Chatbot_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatbot.Chatbot",
	HandlerType: (*ChatbotServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Reply",
			Handler:    _Chatbot_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "chatbot.proto",
}
