// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package reaction

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReactionClient is the client API for Reaction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReactionClient interface {
	Run(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error)
}

type reactionClient struct {
	cc grpc.ClientConnInterface
}

func NewReactionClient(cc grpc.ClientConnInterface) ReactionClient {
	return &reactionClient{cc}
}

func (c *reactionClient) Run(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, "/reaction.Reaction/Run", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReactionServer is the server API for Reaction service.
// All implementations must embed UnimplementedReactionServer
// for forward compatibility
type ReactionServer interface {
	Run(context.Context, *Request) (*Result, error)
	mustEmbedUnimplementedReactionServer()
}

// UnimplementedReactionServer must be embedded to have forward compatible implementations.
type UnimplementedReactionServer struct {
}

func (UnimplementedReactionServer) Run(context.Context, *Request) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Run not implemented")
}
func (UnimplementedReactionServer) mustEmbedUnimplementedReactionServer() {}

// UnsafeReactionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReactionServer will
// result in compilation errors.
type UnsafeReactionServer interface {
	mustEmbedUnimplementedReactionServer()
}

func RegisterReactionServer(s grpc.ServiceRegistrar, srv ReactionServer) {
	s.RegisterService(&Reaction_ServiceDesc, srv)
}

func _Reaction_Run_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReactionServer).Run(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/reaction.Reaction/Run",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReactionServer).Run(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Reaction_ServiceDesc is the grpc.ServiceDesc for Reaction service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Reaction_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "reaction.Reaction",
	HandlerType: (*ReactionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Run",
			Handler:    _Reaction_Run_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "reaction.proto",
}
